# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', models.CharField(max_length=200)),
                ('text_2', models.CharField(max_length=200)),
                ('text_3', models.CharField(max_length=200)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='type_id',
        ),
        migrations.AlterField(
            model_name='item',
            name='poster_src',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Item'),
        ),
        migrations.AddField(
            model_name='review',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Type'),
        ),
    ]
