# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161219_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='poster_src',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
