# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161219_2206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Kind',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='type_id',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='type_id',
            new_name='kind',
        ),
    ]
