# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161226_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='kind',
        ),
    ]
